config/routes.rb
Rails.application.routes.draw do
    root 'novels#index'
    resources :novels do
        resources :comments, :only => [:create, :destroy]
    end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :novel
end

app/models/novel.rb
class Novel < ApplicationRecord
    has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_novel

    def create
        @post.comments.create! comments_params
        redirect_back(fallback_location: @novel)
    end

    def destroy
        @post.comments.destroy params[:id]
        redirect_back(fallback_location: @novel)
    end

     private
        def set_novel
            @post = Novel.find(params[:novel_id])
        end

         def comments_params
            params.required(:comment).permit(:content)
        end
end

app/controllers/novels_controller.rb
class NovelsController < ApplicationController
  before_action :set_novel, only: [:show, :edit, :update, :destroy]

  # GET /novels
  # GET /novels.json
  def index
    @novels = Novel.all
  end

  # GET /novels/1
  # GET /novels/1.json
  def show
  end

  # GET /novels/new
  def new
    @novel = Novel.new
  end

  # GET /novels/1/edit
  def edit
  end

  # POST /novels
  # POST /novels.json
  def create
    @novel = Novel.new(novel_params)

    respond_to do |format|
      if @novel.save
        format.html { redirect_to @novel, notice: 'Novel was successfully created.' }
        format.json { render :show, status: :created, location: @novel }
      else
        format.html { render :new }
        format.json { render json: @novel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /novels/1
  # PATCH/PUT /novels/1.json
  def update
    respond_to do |format|
      if @novel.update(novel_params)
        format.html { redirect_to @novel, notice: 'Novel was successfully updated.' }
        format.json { render :show, status: :ok, location: @novel }
      else
        format.html { render :edit }
        format.json { render json: @novel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /novels/1
  # DELETE /novels/1.json
  def destroy
    @novel.destroy
    respond_to do |format|
      format.html { redirect_to novels_url, notice: 'Novel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_novel
      @novel = Novel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def novel_params
      params.require(:novel).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/novels_helper.rb
module NovelsHelper
end

app/views/comments/_comment.html.erb
<p><%= comment.content %></p>
<p><%= link_to "Delete", [@novel, comment], method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/comments/_new.html.erb
<%= form_with(model: [ @novel, Comment.new ], remote: true) do |form| %>
    Your Comment:<br>
    <%= form.text_area :content, size: '50x20' %><br>
    <%= form.submit %>
<% end %>  

app/views/layouts/_header.html.erb
<nav class ="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "Novel Post", root_path, class: "navbar-brand" %>
    <button class="nabar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Menu
        </button>
        <div class ="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <%= link_to 'Novels', novels_path, class: "dropdown-item" %>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NovelPost</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render 'layouts/header' %>
      <div class="container">
          <%= yield %>
      </div>
  </body>
</html>

app/views/novels/_form.html.erb
<div data-controller="novel">
    <div class="form-left">
        <%= form_with(model: novel, local:true) do |form| %>
            <% if novel.errors.any? %>
                <div id="error_explanatioin">
                    <h2><%= pluralize(novel.errors.count, "error") %> prohibited this novel from being saved:</h2>
                    
                    <uL>
                        <% novel.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                        <% end %>
                    </uL>
                </div>
            <% end %>
            
            <div class="field">
                <%= form.label :title %>
                <%= form.text_field :title %>
            </div>
            
            <div class="field">
                <%= form.label :content %>
                <%= form.hidden_field :content, id: :novel_content %>
                <trix-editor input="novel_content" data-target="novel.content" data-action="input->novel#content"></trix-editor>
            </div>
            <div class="actions">
                <%= form.submit %>
            </div>
        <% end %>
    </div>
    
    <div class="form-right">
        <h1>Content</h1>
        <div data-target="novel.preview"></div>
    </div>
</div>

<%= javascript_pack_tag 'application.js' %>  

app/views/novels/edit.html.erb
<h1>Editing Novel</h1>

<%= render 'form', novel: @novel %>

<%= link_to 'Show', @novel %> |
<%= link_to 'Back', novels_path %>

app/views/novels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Novels</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @novels.each do |novel| %>
      <tr>
        <td><%= novel.title %></td>
        <td><%= link_to 'Show', novel %></td>
        <td><%= link_to 'Edit', edit_novel_path(novel) %></td>
        <td><%= link_to 'Destroy', novel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Novel', new_novel_path %>

app/views/novels/new.html.erb
<h1>New Novel</h1>

<%= render 'form', novel: @novel %>

<%= link_to 'Back', novels_path %>

app/views/novels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @novel.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @novel.content %>
</p>

<h2>Comments</h2>
    <div id="comments">
        <%= render @novel.comments %>
    </div>

<%= render 'comments/new', novel: @novel %>

<%= link_to 'Edit', edit_novel_path(@novel) %> |
<%= link_to 'Back', novels_path %>